#!/usr/bin/env node
// check-updates.ts — Check for updates for Claude Code, AGY CLI, Codex CLI, and this harness.
// Generated by create-agent-harness.

import { execFile } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { promisify } from "node:util";

const execFilePromise = promisify(execFile);
const projectRoot = process.cwd();

console.log("Checking for updates of Node, Claude Code, AGY, Codex, and Harness...");

/**
 * Compare two dotted version strings numerically. Returns <0, 0, >0.
 *
 * Not a semver library: these are Node release numbers, so a plain numeric
 * compare of the first three components is exactly right and costs no
 * dependency. Missing components read as 0, so "24" < "24.1.0".
 */
export function compareVersions(a: string, b: string): number {
  const parse = (v: string) => String(v).replace(/^v/, "").split(".").map((x) => Number(x) || 0);
  const left = parse(a);
  const right = parse(b);
  for (let i = 0; i < 3; i++) {
    const diff = (left[i] ?? 0) - (right[i] ?? 0);
    if (diff !== 0) return diff;
  }
  return 0;
}

/** The lowest version an `engines` range like ">=22.18" admits, or null. */
export function engineFloor(range: unknown): string | null {
  const m = String(range ?? "").match(/(\d+(?:\.\d+){0,2})/);
  return m ? (m[1] ?? null) : null;
}

/**
 * The newest Node release, from nodejs.org. Best-effort with a short timeout —
 * an offline session must report "check failed", never stall startup.
 */
async function latestNodeVersion(timeoutMs = 4000): Promise<string | null> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  if (typeof timer.unref === "function") timer.unref();
  try {
    const res = await fetch("https://nodejs.org/dist/index.json", { signal: ctrl.signal });
    if (!res.ok) return null;
    const releases = (await res.json()) as Array<{ version?: string }>;
    const newest = releases?.[0]?.version;
    return newest ? String(newest).replace(/^v/, "") : null;
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

function commandName(name: string): string {
  return process.platform === "win32" && ["agy", "claude", "codex", "npm"].includes(name)
    ? `${name}.cmd`
    : name;
}

async function runProcess(command: string, args: string[], timeoutMs = 4000, options: { cwd?: string } = {}) {
  try {
    const { stdout, stderr } = await execFilePromise(commandName(command), args, {
      cwd: options.cwd,
      timeout: timeoutMs,
      windowsHide: true,
    });
    return { stdout: (stdout || "").trim(), stderr: (stderr || "").trim() };
  } catch {
    return null;
  }
}

/**
 * Startup must not stall behind the auto-update, so the subprocess is bounded.
 * How long the write of a few hundred files takes is a property of the host,
 * though — measured at ~1.5s on a laptop and past 60s on a loaded runner with
 * slow disk — and a host that trips the bound is told the update "failed" when
 * it was only slow. Raise it there rather than lose the update.
 */
function updateTimeoutMs(): number {
  const raw = Number(process.env.HARNESS_UPDATE_TIMEOUT_MS);
  return Number.isFinite(raw) && raw > 0 ? raw : 60000;
}

async function runCmd(command: string, args: string[], timeoutMs = 4000) {
  const result = await runProcess(command, args, timeoutMs);
  return result ? result.stdout : null;
}

async function runGit(args: string[], timeoutMs = 4000) {
  const result = await runProcess("git", args, timeoutMs);
  return result ? result.stdout : null;
}

async function runAgyUpdate(timeoutMs = 5000) {
  const result = await runProcess("agy", ["update"], timeoutMs);
  if (!result) return "Error running agy update.";
  return (result.stdout || result.stderr || "").trim();
}

function readJson(file: string): any {
  try {
    return JSON.parse(readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

function shortSha(sha: unknown): string {
  return typeof sha === "string" && sha ? sha.slice(0, 7) : "unknown";
}

function validHarnessSource(sourcePath: string | null | undefined): boolean {
  return Boolean(sourcePath && existsSync(join(sourcePath, "bin", "create.ts")));
}

async function maybePullHarnessSource(sourcePath: string) {
  if (process.env.HARNESS_UPDATE_PULL !== "1") return;

  const status = await runGit(["-C", sourcePath, "status", "--porcelain"], 10000);
  if (status === null) {
    console.log("Harness source pull skipped (git status failed)");
    return;
  }
  if (status !== "") {
    console.log("Harness source pull skipped (source has local changes)");
    return;
  }

  const pulled = await runGit(["-C", sourcePath, "pull", "--ff-only"], 10000);
  if (pulled === null) console.log("Harness source pull skipped (git pull failed)");
}

async function detectCurrentHarnessCommit(stamp: any, sourcePath: string | null, hasSource: boolean): Promise<string | null> {
  if (hasSource && sourcePath) {
    const current = await runGit(["-C", sourcePath, "rev-parse", "HEAD"], 4000);
    if (current && /^[0-9a-f]{40}$/i.test(current)) return current.toLowerCase();
    return null;
  }

  if (stamp.remoteUrl) {
    const ref = stamp.branch || "HEAD";
    const remote = await runGit(["ls-remote", stamp.remoteUrl, ref], 4000);
    const current = remote?.split(/\s+/)[0];
    if (current && /^[0-9a-f]{40}$/i.test(current)) return current.toLowerCase();
  }

  return null;
}

async function printHarnessCheck() {
  const stampPath = resolve(projectRoot, ".harness-version.json");
  if (!existsSync(stampPath)) {
    console.log("Harness check skipped (missing .harness-version.json)");
    return;
  }

  const stamp = readJson(stampPath);
  if (!stamp || typeof stamp !== "object") {
    console.log("Harness check skipped (unparsable .harness-version.json)");
    return;
  }

  const source = readJson(resolve(projectRoot, ".harness", "source.json"));
  const sourcePath = source && typeof source.sourcePath === "string" ? source.sourcePath : null;
  const hasSource = validHarnessSource(sourcePath);

  if (hasSource) await maybePullHarnessSource(sourcePath);

  if (!stamp.commit || !/^[0-9a-f]{40}$/i.test(stamp.commit)) {
    console.log("Harness check skipped (missing stamped commit)");
    return;
  }

  const current = await detectCurrentHarnessCommit(stamp, sourcePath, hasSource);
  if (!current) {
    console.log("Harness check skipped (unable to detect current harness commit)");
    return;
  }

  const harnessVersion = stamp.version || "unknown";
  const stamped = stamp.commit.toLowerCase();
  if (current === stamped) {
    console.log(`✓ Harness v${harnessVersion} is up-to-date (${shortSha(current)})`);
    return;
  }

  console.log(`⚠️  Harness Update Available (v${harnessVersion}): ${shortSha(stamped)} -> ${shortSha(current)}`);

  if (hasSource) {
    const behind = await runGit(["-C", sourcePath, "rev-list", `${stamped}..${current}`, "--count"], 4000);
    if (behind && /^\d+$/.test(behind)) console.log(`   (${behind} commit(s) behind)`);
    console.log(`   Run: git -C ${sourcePath} pull --ff-only`);
    console.log(`   Run: node ${join(sourcePath, "bin", "create.ts")} . --update --no-install`);
  }

  if (process.env.HARNESS_AUTO_UPDATE !== "1" || !hasSource) return;

  const updated = await runProcess(
    process.execPath,
    [join(sourcePath, "bin", "create.ts"), projectRoot, "--update", "--no-install"],
    updateTimeoutMs(),
    { cwd: projectRoot },
  );
  if (updated) {
    console.log(`✓ Harness auto-update applied (${shortSha(stamped)} -> ${shortSha(current)})`);
  } else {
    console.log("Harness auto-update skipped (create-agent-harness --update failed)");
  }
}

async function main() {
  // Run all checks in parallel to minimize session startup latency.
  const [
    localClaudeRaw,
    latestClaude,
    localCodexRaw,
    latestCodex,
    agyResult,
    harnessResult,
    latestNode,
  ] = await Promise.all([
    runCmd("claude", ["--version"]),
    runCmd("npm", ["show", "@anthropic-ai/claude-code", "version"]),
    runCmd("codex", ["--version"]),
    runCmd("npm", ["show", "@openai/codex", "version"]),
    runAgyUpdate(),
    printHarnessCheck(),
    latestNodeVersion(),
  ]);
  void harnessResult;

  const localClaude = localClaudeRaw ? (localClaudeRaw.match(/([\d.]+)/)?.[1] || null) : null;
  const localCodex = localCodexRaw ? (localCodexRaw.match(/([\d.]+)/)?.[1] || null) : null;

  console.log("\n================ Update Check Results ================");

  // Node first: everything below runs ON it, and a host under the floor cannot
  // execute the harness at all — the scripts ship as TypeScript and rely on
  // native type stripping. That is a blocker, not an "update available".
  const localNode = process.versions.node;
  const floor = engineFloor(readJson(resolve(projectRoot, ".harness-version.json"))?.minNode);
  if (floor && compareVersions(localNode, floor) < 0) {
    console.log(`❌ Node ${localNode} is below the ${floor} this harness requires — its scripts cannot run.`);
    console.log("   Install the current release: https://nodejs.org/en/download");
  } else if (latestNode && compareVersions(localNode, latestNode) < 0) {
    console.log(`⚠️  Node Update Available: ${localNode} -> ${latestNode}`);
    console.log("   Install the current release: https://nodejs.org/en/download");
  } else if (latestNode) {
    console.log(`✓ Node is up-to-date (${localNode})`);
  } else {
    console.log(`✓ Node ${localNode} (remote check failed — offline?)`);
  }

  // Claude Code output formatting
  if (localClaude && latestClaude) {
    if (localClaude !== latestClaude) {
      console.log(`⚠️  Claude Code Update Available: ${localClaude} -> ${latestClaude}`);
      console.log("   Run: npm install -g @anthropic-ai/claude-code");
    } else {
      console.log(`✓ Claude Code is up-to-date (${localClaude})`);
    }
  } else if (!localClaude && latestClaude) {
    console.log(`⚠️  Claude Code is not installed locally (Latest version: ${latestClaude})`);
    console.log("   Run: npm install -g @anthropic-ai/claude-code");
  } else if (localClaude && !latestClaude) {
    console.log(`✓ Claude Code is installed (${localClaude}) but remote check failed (offline?)`);
  } else {
    console.log("❌ Claude Code check failed (Local: Not found, Remote: Not found)");
  }

  // Codex output formatting
  if (localCodex && latestCodex) {
    if (localCodex !== latestCodex) {
      console.log(`⚠️  Codex Update Available: ${localCodex} -> ${latestCodex}`);
      console.log("   Run: npm install -g @openai/codex");
    } else {
      console.log(`✓ Codex is up-to-date (${localCodex})`);
    }
  } else if (!localCodex && latestCodex) {
    console.log(`⚠️  Codex is not installed locally (Latest version: ${latestCodex})`);
    console.log("   Run: npm install -g @openai/codex");
  } else if (localCodex && !latestCodex) {
    console.log(`✓ Codex is installed (${localCodex}) but remote check failed (offline?)`);
  } else {
    console.log("❌ Codex check failed (Local: Not found, Remote: Not found)");
  }

  console.log("\nAGY CLI Status:");
  console.log(agyResult || "No output from agy update.");
  console.log("======================================================\n");
}

main().catch((err) => {
  console.error("Failed to run update check:", err);
  process.exitCode = 0;
});
